--create table if not exists user2(userid int,username varchar(20),password varchar(20),role varchar(20),primary key(userid));
--insert into user2 values(1,'Gajanan','Gajanan','admin');
--insert into user2 values(2,'Gajanan','Gajanan','admin');
create table if not exists user(id int, username varchar(20),password varchar(20),role varchar(20),primary key(id));
--insert into user values(1,'Gajanan','Gajanan','admin');
--create SEQUENCE idOfProduct1 increment by 1 start with 101;
create table if not exists product
								(
									product_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100, INCREMENT BY 1)primary key
									,product_name varchar(20)
									,description varchar(20)
									,wholesale_price varchar(20)
									,retail_price varchar(20)
									,discount varchar(20)
									,stock varchar(20)
								);

								
								
--insert into product(
--						 product_id
--						,product_name
--						,description
--						,wholesale_price
--						,retail_price
--						,discount
--						,stock
--					) 
--					values
--					(
--						null
--						,'mobile'
--						,'0'
--						,'apple'
---						,'30000'
--						,'5'
--						,'26500'
--					);
					
					
insert into product values(null
						,'mobile'
						,'0'
						,'apple'
						,'30000'
						,'5'
						,'26500');
						
											
insert into product values(null
						,'Screen Gard'
						,'0'
						,'Moto5'
						,'30'
						,'5'
						,'26');
--insert into product values(105,'Mobile','Apple',30000,26500.50,0,5);
--insert into product values(102,'Camera','Sony',35000,29000.50,5,5);
--insert into product values(103,'Mobile','Samsung',20000,18000.50,0,5);
--insert into product values(104,'Laptop','Apple',65000,60000.50,0,5);

--create table if not exists customer(customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 100,INCREMENT BY 1) primary key,customer_name varchar(20));
create table if not exists customer
					(
						 customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1)primary key
						,customer_name varchar(20)
						,address varchar(20)
						,mobile_no varchar(20)
						,city varchar(20)
						,country varchar(20)
					);

--insert into customer(customer_id,customer_name,address,mobile_no,city,country) values(101,'Gajanan','kfc baner','7709635664','pune','India');
--insert into customer(customer_id,customer_name,address,mobile_no,city,country) values(102,'Harshal','kfc baner','7709635664','pune','India');
--insert into customer(customer_id,customer_name) values(IDENTITY()+1,'Gajanan');
--insert into customer(customer_id,customer_name) values(IDENTITY()+1,'Gajanan');

insert into customer values(null,'kfc baner','pune','India','Vidya','7709635664');
insert into customer values(null,'kfc baner','pune','India','Gajanan','7709635664');
insert into customer values(null,'kfc baner','pune','India','Akshay','9049131751');
insert into customer values(null,'kfc baner','pune','India','Kailash','7709635664');

